version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rover-mission-control-frontend:latest
    container_name: rmc-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - REACT_APP_WS_URL=ws://backend:8000
    depends_on:
      - backend
    networks:
      - rover-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rover-mission-control-backend:latest
    container_name: rmc-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/rover_platform.db
      - CORS_ORIGINS=http://localhost:3000,http://frontend
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - rover-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  rover-network:
    driver: bridge

volumes:
  data:
  logs: