# OPA Configuration
services:
  - name: "security-policies"
    url: "http://localhost:8181"
    
bundles:
  security:
    resource: "/policies"
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

decision_logs:
  console: true
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 10

status:
  console: true

plugins:
  envoy_ext_authz_grpc:
    addr: ":9191"
    query: "data.docker.security.allow"